### ISSUE TITLE
What GPL version?

### ISSUE THREAD

**Issue by kozross** [stefanct/sglib#5]
You specify GPL as a licensing option, but not which version. This is quite germane to its re-use, so a clarification would be appreciated.

**Comment by stefanct** [comment]
I do not specify anything. The original author did (not precisely) indicate that he released this library under "the" GPL. I don't know which version and I don't care a lot because I am not using it. If anyone is able to contact the original author and get him to state the exact version I am happy to add an appropriate LICENSE file... until then this is a WONTFIX.
